name: Testes automáticos

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

  steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: npm install

    - name: Rodar testes
      run: npm test
