name: Testes Automáticos  # Nome do workflow

on:  
  push:
    branches:
      - main  # Dispara quando houver push na branch main

jobs:
  test:
    runs-on: ubuntu-latest  # Usa um ambiente Ubuntu

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test
